#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
QTBASE="${1:-${ROOT}/build/qtbase-switch}"
QTDECLARATIVE="${2:-${ROOT}/build/qtdeclarative-switch}"
OUT="${3:-${QTBASE}/qt-switch-artifacts.mk}"

pick() {
    local root="$1" name="$2" result
    result="$(find "$root" -type f -name "$name" -print -quit)"
    [ -n "$result" ] || { echo "Missing Qt artifact $name under $root" >&2; exit 1; }
    printf '%s' "$result"
}

cat > "$OUT" <<EOF
# Generated by scripts/generate-qt-artifacts.sh. Do not edit.
QT_RSRC_1 := $(pick "$QTBASE" qrc_qpdf_init.cpp.obj)
QT_RSRC_2 := $(pick "$QTBASE" qrc_gui_shaders_init.cpp.obj)
EOF

if [ -d "$QTDECLARATIVE" ]; then
cat >> "$OUT" <<EOF
QT_QML_PLUGIN_INIT := $(pick "$QTDECLARATIVE" qmlplugin_init.cpp.obj)
QT_QMLMODELS_PLUGIN_INIT := $(pick "$QTDECLARATIVE" modelsplugin_init.cpp.obj)
QT_QMLWORKER_PLUGIN_INIT := $(pick "$QTDECLARATIVE" workerscriptplugin_init.cpp.obj)
QT_QML_RSRC := $(pick "$QTDECLARATIVE" qrc_qmake_QtQml_init.cpp.obj)
QT_QMLMODELS_RSRC := $(pick "$QTDECLARATIVE" qrc_qmake_QtQml_Models_init.cpp.obj)
QT_QMLWORKER_RSRC := $(pick "$QTDECLARATIVE" qrc_qmake_QtQml_WorkerScript_init.cpp.obj)
QT_QUICK_RSRC := $(pick "$QTDECLARATIVE" qrc_qmake_QtQuick_init.cpp.obj)
QT_QML_CORE_RSRC := $(pick "$QTDECLARATIVE" qrc_qmake_QML_init.cpp.obj)
QT_QML_RSRC_OBJ := $(pick "$QTDECLARATIVE" qrc_qmake_QtQml.cpp.obj)
QT_QMLMODELS_RSRC_OBJ := $(pick "$QTDECLARATIVE" qrc_qmake_QtQml_Models.cpp.obj)
QT_QMLWORKER_RSRC_OBJ := $(pick "$QTDECLARATIVE" qrc_qmake_QtQml_WorkerScript.cpp.obj)
QT_QUICK_RSRC_OBJ := $(pick "$QTDECLARATIVE" qrc_qmake_QtQuick.cpp.obj)
EOF
fi
